language: c
dist: trusty

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      libsysfs-dev
      libxml2
      libxml2-dev
      libssl-dev
      libcurl3-dev
      libp11-dev
      librtlsdr-dev
      libusb-1.0-0-dev
      libjansson-dev

script:
  - rm -rf ./jitterentropy-library/*
  - ./autogen.sh
  - ./configure
  - make
  - make check || (cat tests/rngtesturandom.sh.log &&
    cat tests/rngtestzero.sh.log && cat ./tests/test-suite.log)
  - sudo make install
